GET http://localhost:3000/autos HTTP/1.1

###
GET http://localhost:3000/autos/1 HTTP/1.1

###
POST http://localhost:3000/autos HTTP/1.1
Content-Type: application/json

{
  "model": "Tesla Model S",
  "year": 2024,
  "color": "Red"
}

###PUT http://localhost:3000/autos/3 HTTP/1.1
Content-Type: application/json

{
  "model": "Tesla Model X",
  "year": 2023,
  "color": "Black"
}
###
DELETE http://localhost:3000/autos/3 HTTP/1.1